// packages/vue/src/index.vue
<script setup lang="ts">
import {
	addThemeIfNeeded,
	initMonacoIfNeeded,
	monaco, MonacoType, OtherCfg,
	ThemeAddProp, WrappedEditor
} from "@uwu/simple-monaco-core";
import { onUnmounted, watchEffect } from "vue";

const props = defineProps<{
	lang: string;
	modelValue: string;
	readonly?: boolean;
	theme?: ThemeAddProp;
	otherCfg?: OtherCfg;
	height?: string;
	width?: string;
	noCDN?: MonacoType;
	filename: string;
}>();
const emit = defineEmits<{
	(event: "update:modelValue", value: string): void;
	(event: "editorRef", ed: WrappedEditor): void;
}>();

let dispose: () => void;
let cancelInit = false;

let firstRun = true;
const refCb = async (elem: HTMLDivElement) => {
	// vue why does this run more than once??? oh well.
	if (!firstRun) return;
	firstRun = false;

	await initMonacoIfNeeded(props.noCDN);
	await addThemeIfNeeded(props.theme);
	if (cancelInit) return;

	const ed = new WrappedEditor(elem, props.lang, props.modelValue, props.filename, props.readonly, props.theme, props.otherCfg);

	dispose = () => ed.editor.dispose();

	ed.onChange((v) => emit("update:modelValue", v));
	watchEffect(() => ed.setReadOnly(props.readonly));
	watchEffect(() => ed.setValue(props.modelValue));
	watchEffect(() => ed.setTheme(props.theme));
	watchEffect(() => ed.setLanguage(props.lang));
	watchEffect(() => ed.setFilename(props.filename));
	watchEffect(() => ed.setOtherCfg(props.otherCfg));

	emit("editorRef", ed);
};

onUnmounted(() => dispose?.());
</script>

<template>
	<div :ref="refCb" :style="{ width: props.width ?? '30rem', height: props.height ?? '10rem' }" />
</template>

// packages/svelte/src/index.svelte
<script lang="ts">
	import {onDestroy, onMount} from "svelte";
	import {Readable, Writable} from "svelte/store";
	import {
		addThemeIfNeeded,
		initMonacoIfNeeded,
		OtherCfg,
		WrappedEditor
	} from "@uwu/simple-monaco-core";
	import type {MonacoType, ThemeAddProp} from "@uwu/simple-monaco-core";

	export let
		lang: string,
		value: Readable<string> | Writable<string>,
		readonly: boolean = false,
		theme: ThemeAddProp = undefined,
		otherCfg: OtherCfg = {},
		height: string = "10rem",
		width: string = "30rem",
    	noCDN: MonacoType = undefined,
		filename: string,
		editorRef: ((w: WrappedEditor) => void) | Writable<WrappedEditor>;

	let ed: WrappedEditor;

	const isWritable = <T>(s: Readable<T>): s is Writable<T> => s["set"];

	let elem: HTMLDivElement;
	let cancelInit = false;
	onMount(async () => {
		await initMonacoIfNeeded(noCDN);
		await addThemeIfNeeded(theme);

		if (cancelInit) return;

		ed = new WrappedEditor(elem, lang, $value, filename, readonly, theme, otherCfg);

		ed.onChange((v) => isWritable(value) && ($value = v));
	});

	$: if (ed) {
			if (typeof editorRef === "function") editorRef(ed);
			else editorRef.set(ed); // svelte is not smart enough to let me use $ syntax here.
		}

	$: ed?.setValue($value);
	$: ed?.setReadOnly(readonly);
	$: ed?.setTheme(theme);
	$: ed?.setLanguage(lang);
	$: ed?.setFilename(filename);
  $: ed?.setOtherCfg(otherCfg);

	onDestroy(() => {
		cancelInit = true;
		ed?.editor.dispose();
	});
</script>

<div
  bind:this={elem}
  style:width
  style:height
></div>
