// test-app/src/main.tsx
import React, { useState } from "react";
import ReactDOM from "react-dom/client";
import Monaco from "../../src";

function App() {
  const [val, setVal] = useState("");
  const [lang, setLang] = useState("javascript");
  const [theme, setTheme] = useState("Monokai");
  const [ro, setRo] = useState(false);

  return (
    <>
      <h1>Monaco solid test</h1>
      <Monaco
        value={val}
        lang={lang}
        valOut={setVal}
        theme={theme}
        readonly={ro}
      />
      <pre>
        <code>{val}</code>
      </pre>
      <button onClick={() => setVal("")}>clear</button>
      <input type="text" onChange={(e) => setLang(e.target.value)} />
      <input type="text" onChange={(e) => setTheme(e.target.value)} />
      <input
        id="ro"
        type="checkbox"
        onChange={(e) => setRo(e.target.checked)}
      />
      <label htmlFor="ro">readonly</label>
    </>
  );
}

ReactDOM.createRoot(document.querySelector("#root") as HTMLElement).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

// packages/solid-test/src/index.tsx
/* @refresh reload */
import { createSignal } from "solid-js";
import { render } from "solid-js/web";
import Monaco from "../../src";

render(() => {
  const [val, setVal] = createSignal("");
  const [lang, setLang] = createSignal("javascript")
  const [theme, setTheme] = createSignal("Monokai")
  const [ro, setRo] = createSignal(false)

  return (
    <>
      <h1>Monaco solid test</h1>
      <Monaco value={val()} lang={lang()} valOut={setVal} theme={theme()} readonly={ro()} />
      <pre>
        <code>{val()}</code>
      </pre>
      <button onclick={() => setVal("")}>clear</button>
      <input type="text" onchange={e => setLang((e.target as HTMLInputElement).value)} />
      <input type="text" onchange={e => setTheme((e.target as HTMLInputElement).value)} />
      <input id="ro" type="checkbox" onchange={e => setRo((e.target as HTMLInputElement).checked)} />
      <label for="ro">readonly</label>
    </>
  );
}, document.querySelector("body") as HTMLElement);
