// packages/solid/src/index.tsx
import { createEffect, on, onCleanup } from "solid-js";
import { addThemeIfNeeded, initMonacoIfNeeded, monaco } from "./monaco";
import type { MonacoCompType } from "./types";

export default ((props) => {
  let dispose: () => void;
  let cancelInit = false;

  const refCb = async (elem: HTMLDivElement) => {
    await initMonacoIfNeeded(props.noCDN);

    await addThemeIfNeeded(props.theme);

    if (cancelInit) return;

    const ed = monaco.editor.create(elem, {
      language: props.lang,
      value: props.value,
      readOnly: props.readonly ?? false,
      theme: props.theme,
      ...props.otherCfg,
    });

    dispose = () => ed.dispose();

    // stops syntax highlighting flickering
    //let valueAntiflicker = false;

    ed.onDidChangeModelContent(() => {
      //valueAntiflicker = true;
      props.valOut?.(ed.getValue());
      //valueAntiflicker = false;
    });

    createEffect(() => ed.updateOptions({ readOnly: props.readonly }));

    createEffect(() => {
      if (props.value !== ed.getValue()) ed.setValue(props.value);
    });

    createEffect(async () => {
      await addThemeIfNeeded(props.theme);
      ed.updateOptions({ theme: props.theme });
    });

    createEffect(() => {
      const model = ed.getModel();
      if (!model) return;
      monaco.editor.setModelLanguage(model, props.lang);
      ed.setModel(model);
    });

    createEffect(() => props.otherCfg && ed.updateOptions(props.otherCfg));
  };

  onCleanup(() => {
    cancelInit = true;
    dispose?.();
  });

  return (
    <div
      ref={refCb}
      style={{ width: props.width ?? "30rem", height: props.height ?? "10rem" }}
    />
  );
}) as MonacoCompType;

// src/index.tsx
import { IStandaloneCodeEditor, MonacoCompType } from "./types";
import { useEffect, useRef } from "react";
import { addThemeIfNeeded, initMonacoIfNeeded, monaco } from "./monaco";

export default ((props) => {
  const dispose = useRef<() => void>();
  const cancelInit = useRef<boolean>();
  const ed = useRef<IStandaloneCodeEditor>();

  const refCb = async (elem: HTMLDivElement) => {
    if (!elem) {
      // unmount
      cancelInit.current = true;
      dispose.current?.();
      return;
    }

    await initMonacoIfNeeded(props.noCDN);

    await addThemeIfNeeded(props.theme);

    if (cancelInit) return;

    ed.current = monaco.editor.create(elem, {
      language: props.lang,
      value: props.value,
      readOnly: props.readonly ?? false,
      theme: props.theme,
      ...props.otherCfg,
    });

    dispose.current = () => ed.current.dispose();

    ed.current.onDidChangeModelContent(() =>
      props.valOut?.(ed.current.getValue())
    );
  };

  useEffect(
    () => ed.current?.updateOptions({ readOnly: props.readonly }),
    [props.readonly]
  );

  useEffect(() => {
    if (props.value !== ed.current?.getValue())
      ed.current?.setValue(props.value);
  }, [props.value]);

  useEffect(() => {
    addThemeIfNeeded(props.theme).then(() =>
      ed.current?.updateOptions({ theme: props.theme })
    );
  }, [props.theme]);

  useEffect(() => {
    const model = ed.current?.getModel();
    if (!model) return;
    monaco.editor.setModelLanguage(model, props.lang);
    ed.current.setModel(model);
  }, [props.lang]);

  useEffect(
    () => props.otherCfg && ed.current?.updateOptions(props.otherCfg),
    [props.otherCfg]
  );

  return (
    <div
      ref={refCb}
      style={{
        width: props.width ?? "30rem",
        height: props.height ?? "10rem",
      }}
    />
  );
}) as MonacoCompType;
