// packages/svelte/src/index.svelte
<script lang="ts">
	import {onDestroy, onMount} from "svelte";
	import {Readable, Writable} from "svelte/store";
	import type {CfgOpts, IStandaloneCodeEditor} from "./types";
	import {addThemeIfNeeded, initMonacoIfNeeded, monaco} from "./monaco";
	import type {Monaco} from "@monaco-editor/loader";

	export let
		lang: string,
		value: Readable<string> | Writable<string>,
		readonly: boolean = false,
		theme: string = undefined,
		otherCfg: CfgOpts = {},
		height: string = "10rem",
		width: string = "30rem",
    noCDN: Monaco = undefined;

	let ed: IStandaloneCodeEditor;

	const isWritable = <T>(s: Readable<T>): s is Writable<T> => s["set"];

	let elem: HTMLDivElement;
	let cancelInit = false;
	onMount(async () => {
		await initMonacoIfNeeded(noCDN);
		await addThemeIfNeeded(theme);

		if (cancelInit) return;

		ed = monaco.editor.create(elem, {
			language: lang,
			value: $value,
			readOnly: readonly,
			theme,
			...otherCfg
		});

		ed.onDidChangeModelContent(() => isWritable(value) && ($value = ed.getValue()));
	});

	$: if ($value !== ed?.getValue()) ed?.setValue($value);
	$: ed?.updateOptions({readOnly: readonly});
	$: addThemeIfNeeded(theme).then(() => ed?.updateOptions({theme}));

	$: {
		const model = ed?.getModel();
		if (model) {
			monaco.editor.setModelLanguage(model, lang);
			ed.setModel(model);
		}
	}

	onDestroy(() => {
		cancelInit = true;
		ed.dispose();
	});
</script>

<div
  bind:this={elem}
  style:width
  style:height
></div>

// src/index.tsx
import { IStandaloneCodeEditor, MonacoCompType } from "./types";
import { useEffect, useRef } from "react";
import { addThemeIfNeeded, initMonacoIfNeeded, monaco } from "./monaco";

export default ((props) => {
  const dispose = useRef<() => void>();
  const cancelInit = useRef<boolean>();
  const ed = useRef<IStandaloneCodeEditor>();

  const refCb = async (elem: HTMLDivElement) => {
    if (!elem) {
      // unmount
      cancelInit.current = true;
      dispose.current?.();
      return;
    }

    await initMonacoIfNeeded(props.noCDN);

    await addThemeIfNeeded(props.theme);

    if (cancelInit) return;

    ed.current = monaco.editor.create(elem, {
      language: props.lang,
      value: props.value,
      readOnly: props.readonly ?? false,
      theme: props.theme,
      ...props.otherCfg,
    });

    dispose.current = () => ed.current.dispose();

    ed.current.onDidChangeModelContent(() =>
      props.valOut?.(ed.current.getValue())
    );
  };

  useEffect(
    () => ed.current?.updateOptions({ readOnly: props.readonly }),
    [props.readonly]
  );

  useEffect(() => {
    if (props.value !== ed.current?.getValue())
      ed.current?.setValue(props.value);
  }, [props.value]);

  useEffect(() => {
    addThemeIfNeeded(props.theme).then(() =>
      ed.current?.updateOptions({ theme: props.theme })
    );
  }, [props.theme]);

  useEffect(() => {
    const model = ed.current?.getModel();
    if (!model) return;
    monaco.editor.setModelLanguage(model, props.lang);
    ed.current.setModel(model);
  }, [props.lang]);

  useEffect(
    () => props.otherCfg && ed.current?.updateOptions(props.otherCfg),
    [props.otherCfg]
  );

  return (
    <div
      ref={refCb}
      style={{
        width: props.width ?? "30rem",
        height: props.height ?? "10rem",
      }}
    />
  );
}) as MonacoCompType;
